### ISSUE TITLE
`hasState` reports `false` when state is `undefined`

### ISSUE THREAD

**Issue by bakkot** [zenparsing/hidden-state#2]
I found this surprising, though I guess it might be intended.

**Comment by zenparsing** [comment]
Right, the way the overloaded function works, `undefined` can never be set as the state value (`undefined` triggers the get overload).

It's a jQuery-ish API, which might be a bit unfashionable these days.

**Comment by bakkot** [comment]
Ah, right. Well, easy enough to work around, I suppose.

**Comment by zenparsing** [comment]
It's probably confusing in the situation where you have `hidden(obj, somethingThatMightBeUndefined)`, so maybe it should be overloaded based on the number of args provided.
